title: "Kankakee Community College"
site_name: "Finish"
port: 3000
public-url: "http://finish.kcc.edu" ## This gets generated into the link that displays in the footer (the one above the social icons)
url: 'https://finish.kcc.edu' ## NO TRAILING SLASHES!!/<--nope
timezone: America/Chicago
theme: "landing-page-gem"
google-tag_key: GTM-NZWZW6F
#core_site: true
custom_site_js: false
custom_site_styling: true
contact_phone: 815-802-8508 # 8500 is main Advising/student services number
#translate: true ## Uncomment to activate Google Translate Powers!!
permalink: pretty
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
# Delete this comment and place description on this line
baseurl: "" # the subpath of your site, e.g. /blog
# include:
#   - "_pages"
#   - "_posts"

# include future posts? (true or false)
future: false
# Build settings
markdown: kramdown

# include:

exclude:
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "package-lock.json"
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "webpack.config.js"
  - "WEBPACK-BABEL-COREJS_INFO.md"
  - "siteicon.png"
  - "page-startups"
  - "UPDATE_PROCEDURE.md"
  - "ruby-version.txt"
  - "buildtools/"
  - "postcss.config.js"

uploads_dir: "uploads/" # specifies the default uploads directory for CloudCannon

_comments:
  layout: Do NOT modify layouts. It may break things.
  baseurl: Do NOT modify baseurl. It WILL break all page links.
  description: "Descriptions are seen by search engines like Google and displayed in search results"

_options: # The CloudCannon options key
  layout: # We don't want users changing these!!
    hidden: true
  baseurl: # We don't want users changing these!!
    hidden: true
  translate:
    hidden: true # Prevent CloudCannon Users from randomly turning translate on in their site.
  sheet_key:
    hidden: true
  content:
    format: p h2 h3 h4 h5 h6 pre address div
    bold: true
    italic: true
    underline: true
    subscript: true
    superscript: true
    indent: true
    outdent: true
    image: true
    table: true
    left: align-left
    center: center-this-text
    right: align-right
    removeformat: true
    link: true
    numberedlist: true
    bulletedlist: true
    undo: true
    redo: true
    styles: /assets/css/content.css
  _block:
    format: p h2 h3 h4 h5 h6 pre address
    bold: true
    italic: true
    underline: true
    subscript: true
    superscript: true
    indent: true
    outdent: true
    image: true
    table: true
    left: align-left
    center: center-this-text
    right: align-right
    removeformat: true
    link: true
    numberedlist: true
    bulletedlist: true
    undo: true
    redo: true
    styles: /assets/css/content.css
  _text:
    bold: true
    italic: true
    removeformat: true
    link: true
    undo: true
    redo: true
    underline: true
    strike: true
    subscript: true
    superscript: true
